name: Learn Workflows

on:
  workflow_dispatch:
    inputs: 
      version:
        description: 'Version'     
        type: text
        required: true
  
    
jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - run: echo ${{ github.event.inputs.version }}
    - run: echo $GITHUB_WORKSPACE
    - run: echo ${{ github }}
    - run: echo "$GITHUB.REPOSITORY"
    - run: echo "$GITHUB.REPOSITORY_OWNER"
    - name: Dump GitHub context
      env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      run: 
        echo "$GITHUB_CONTEXT"
    - run: dir
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run build development.cmd
      run: |
        "build/build development.cmd"
        
    # - run: npm install -g @babel/core
    # - run: echo done
    
    
