name: Learn Workflows

on:
    workflow_dispatch:
        inputs: 
            version:
                description: | 
                    Version: 
                    <div>It’s common practice to prefix your version names with the letter v. Some good tag names might be v1.0.0 or v2.3.4.<div>
                type: text
                required: true
  
    
jobs:
    build:
        name: build v${{ github.event.inputs.version }}
        runs-on: windows-latest
        
        #strategy:
        #    matrix:
        #        node-version: [16.x]

        steps:
        - uses: actions/checkout@v3
        - run: $github.event.inputs.version
        - run: echo ${{ github.event.inputs.version }}
        - name: Dump GitHub context
          env:
                GITHUB_CONTEXT: ${{ toJson(github) }}
          run: 
                echo "$GITHUB_CONTEXT"


        - run: dir
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
                node-version: 16.x

        - name: Cache dependencies
          uses: actions/cache@v3
          with:
            path: ~/.npm
            key: npm-${{ hashFiles('package-lock.json') }}
            restore-keys: npm-

        - name: Install dependencies
          shell: cmd
          run: |
            npm install intell-node

        - name: Run build development.cmd
          shell: cmd
          env: 
            API_KEY: ${{ secrets.GITHUB_TOKEN }}
            VERSION2: ${{ github.event.inputs.version }}
          run: |
            cd build
            set
            "build development.cmd"
            
        
        # - run: npm install -g @babel/core
        # - run: echo done
    
    




    release:
        name: release v${{ github.event.inputs.version }}
        runs-on: windows-latest
        needs: build
        steps:
            - run: dir